FROM node:18

WORKDIR /app

# Instala dependências do Node/Express
COPY package*.json ./
RUN npm install

# Copia e builda o Angular (umi-modal)
COPY umi-modal ./umi-modal
WORKDIR /app/umi-modal
RUN npm install && npm run build:elements

# Volta para a raiz e copia o restante
WORKDIR /app
COPY . .

EXPOSE 3333
CMD ["node", "app.js"]